export const Questions = [
    {
        prompt: "What is the capital of France?",
        optionA: "Madrid",
        optionB: "London",
        optionC: "Berlin",
        optionD: "Paris",
        answer: "optionD",
    },
    {
        prompt: "Which of this is not a programming language?",
        optionA: "Python",
        optionB: "JavaScript",
        optionC: "MC-03",
        optionD: "Java",
        answer: "optionC",
    },
    {
        prompt: "Which of this is not a javascript framework?",
        optionA: "React",
        optionB: "Angular",
        optionC: "Vue",
        optionD: "Java",
        answer: "optionD",
    },
    {
        prompt: "What is the chemical symbol for water?",
        optionA: "CO2",
        optionB: "H2O",
        optionC: "O2",
        optionD: "H2",
        answer: "optionB",
    },
    {
        prompt: "What is the largest mammal in the world?",
        optionA: "Elephant",
        optionB: "Blue whale",
        optionC: "Giraffe",
        optionD: "Rhino",
        answer: "optionB",
    },
    {
        prompt: "Which element is said to keep bones strong?",
        optionA: "Calcium",
        optionB: "Iron",
        optionC: "Oxygen",
        optionD: "Hydrogen",
        answer: "optionA",
    },
    {
        prompt: "Which country invented tea?",
        optionA: "India",
        optionB: "England",
        optionC: "China",
        optionD: "Turkey",
        answer: "optionC",
    },
    {
        prompt: "What is the smallest planet in our solar system?",
        optionA: "Mars",
        optionB: "Jupiter",
        optionC: "Venus",
        optionD: "Mercury",
        answer: "optionD",
    },
    {
        prompt: "Which planet is known as the Red Planet?",
        optionA: "Venus",
        optionB: "Mars",
        optionC: "Jupiter",
        optionD: "Mercury",
        answer: "optionB",
    },
    {
        prompt: "Which of this is not a javascript framework?",
        optionA: "React",
        optionB: "Angular",
        optionC: "Vue",
        optionD: "Java",
        answer: "optionD",
    },

];